<a href="https://colab.research.google.com/github/AnnaYCG99/Introciencia-de-Datos/blob/main/Viernes_23_08_24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Ejemolos de listas

Números=[1, 2, 3, 4, 5]
Nombres=["Anna", "Dulce", "Yael"]
Mixta=[10, "Python", 3.14, True]

In [ ]:
print(Números[4])
print(Nombres[2])

5
Yael


In [ ]:
datos=["Anna", 25, "Morado"]

In [ ]:
print(f"Mi nombre es: {datos[0]}, mi edad es: {datos[1]} y mi color es: {datos[2]}")

Mi nombre es: Anna, mi edad es: 25 y mi color es: Morado


In [ ]:
print("Mi nombre es:", datos[0], ", mi edad es:", datos[1], ", mi color favorito es:", datos[2])

Mi nombre es: Anna , mi edad es: 25 , mi color favorito es: Morado


In [ ]:
a=3
b=6

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)

9
-3
18
0.5
729


In [ ]:
nombre= input("Dame un nombre: ")

Dame un nombre: Anna


In [ ]:
num1= float(input("Dame un número: "))
num2= float(input("Dame otro número: "))

Dame un número: 7.6543
Dame otro número: 8.34679


In [ ]:
print(f"{num1: .2f}")
print(f"{num2: .2f}")

 7.65
 8.35


In [ ]:
x=44
y="Anna"
z=3.1416

In [ ]:
type(z)

float

In [ ]:
#Diccionario, ejemplo básico

estudiante= {
   "nombre":"Anna",
   "edad":25,
   "carrera":"Ciencia de Datos",
   "promedio":9.4
}

In [ ]:
print(f"Mi nombre es: {estudiante['nombre']}, mi edad es: {estudiante['edad']}, mi carrera es: {estudiante['carrera']} y mi promedio es: {estudiante['promedio']}")

Mi nombre es: Anna, mi edad es: 25, mi carrera es: Ciencia de Datos y mi promedio es: 9.4


In [ ]:
#Ejemplo básico de ford con una lista

números= [1,2,3,4,5]
for i in números:
   print(i)

1
2
3
4
5


In [ ]:
texto = "Python"
for letra in texto:
   print(letra)

P
y
t
h
o
n


In [ ]:
for i in range(5): #Itera desde 0 hasta 4
   print(i+1)

1
2
3
4
5


In [ ]:
mesa=["Jimy", "Leo", "Dulce", "Yael", "Anna"]
edad=[24, 22, 17, 18, 25]
color=["Azul", "Morado", "Negro", "Rojo", "Lila"]
hobbie=["Videojuegos", "Videojuegos", "Escuchar música"," Guitarra", "Dormir"]

In [ ]:
for nombre, i, m, n in zip(mesa, edad, color, hobbie):

   print(f"El nombre de mi compañero es: {nombre}, tiene: {i} años, su color favorito es: {m} y su hobbie es: {n}")

El nombre de mi compañero es: Jimy, tiene: 24 años, su color favorito es: Azul y su hobbie es: Videojuegos
El nombre de mi compañero es: Leo, tiene: 22 años, su color favorito es: Morado y su hobbie es: Videojuegos
El nombre de mi compañero es: Dulce, tiene: 18 años, su color favorito es: Negro y su hobbie es: Escuchar música
El nombre de mi compañero es: Yael, tiene: 19 años, su color favorito es: Rojo y su hobbie es:  Guitarra
El nombre de mi compañero es: Anna, tiene: 25 años, su color favorito es: Lila y su hobbie es: Dormir


In [ ]:
for nombre,i in zip(mesa, edad):
   if i==18:
       print(f"{nombre} tiene {i} y ya es de edad en norma")
   elif i<18:
       print(f"{nombre} tiene {i} y no es mayor de edad")
   else:
       print(f"{nombre} tiene {i} y es mayor de edad")

Jimy tiene 24 y es mayor de edad
Leo tiene 22 y es mayor de edad
Dulce tiene 17 y no es mayor de edad
Yael tiene 18 y ya es de edad en norma
Anna tiene 25 y es mayor de edad


In [ ]:
#Fundamentos de matemáticas

# (P or Q) and (notP)

dat=[True, False]

In [ ]:
for P in dat:
   for Q in dat:
      print(f"Cuándo P es: {P} y Q es: {Q} la operación es {(P or Q)and(not P)}")

Cuándo P es: True y Q es: True la operación es False
Cuándo P es: True y Q es: False la operación es False
Cuándo P es: False y Q es: True la operación es True
Cuándo P es: False y Q es: False la operación es False


In [ ]:
for A in dat:
   for B in dat:
      for C in dat:
        print(f"Cuando A es: {A}, B es: {B} y C es:{C} la operación es: {(A and not B) or (C)}")

Cuando A es: True, B es: True y C es:True la operación es: True
Cuando A es: True, B es: True y C es:False la operación es: False
Cuando A es: True, B es: False y C es:True la operación es: True
Cuando A es: True, B es: False y C es:False la operación es: True
Cuando A es: False, B es: True y C es:True la operación es: True
Cuando A es: False, B es: True y C es:False la operación es: False
Cuando A es: False, B es: False y C es:True la operación es: True
Cuando A es: False, B es: False y C es:False la operación es: False


In [ ]:
edad=int(input("¿Cuál es tu edad? "))

if edad==19:
    print("Tienes 19 años")
else:
    print("Tú no tienes 19 años")

¿Cuál es tu edad? 20
Tú no tienes 19 años


In [ ]:
edad=int(input("¿Cuál es tu edad? "))

if edad==19:
    print("Tienes 19 años")
elif edad==21:
    print("Tienes 21 años")
else:
    print("Tú no tienes 19 o 21 años")

¿Cuál es tu edad? 25
Tú no tienes 19 o 21 años


In [ ]:
pip install numpy

In [ ]:
import numpy as np

A=np.array([[4,3,1],[5,2,7],[8,2,9]])
B=np.array([[7,-2,3],[4,1,2],[5,3,1]])
print(A)
print(B)

[[4 3 1]
 [5 2 7]
 [8 2 9]]
[[ 7 -2  3]
 [ 4  1  2]
 [ 5  3  1]]


In [ ]:
print(A+B)

[[11  1  4]
 [ 9  3  9]
 [13  5 10]]


In [ ]:
print(np.dot(A,B))

[[ 45  -2  19]
 [ 78  13  26]
 [109  13  37]]


In [ ]:
from fractions import Fraction
print(Fraction(3,4))

3/4
